version: "3.8"


services:
  web:
    container_name: service-pagamento
    build:
      context: .
    volumes:
      - ".:/app"
      - "/node_modules"
    ports:
      - 3000:3000
    environment:
      AWS_ACCESS_KEY_ID : ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SQS_CANCELAR_PEDIDO : ${AWS_SQS_CANCELAR_PEDIDO}
      AWS_SQS_CONFIRMACAO_PAGAMENTO : ${AWS_SQS_CONFIRMACAO_PAGAMENTO}
      MP_URL: ${MP_URL}
      MP_CLIENT_ID: ${MP_CLIENT_ID}
      MP_CLIENT_SECRET: ${MP_CLIENT_SECRET}
      MP_NOTIFICATION_URL: ${MP_NOTIFICATION_URL}
    depends_on:
      - mongo-db-pagamento
    networks:
        - microservice-fiap
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  mongo-db-pagamento:
    image: mongo:5.0.2
    restart: unless-stopped
    container_name: mongo-db-pagamento
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27020:27017"
    networks:
      - microservice-fiap  

  localstack-pagamento:
    image: localstack/localstack
    container_name: localstack-pagamento
    ports:
      - "4567:4566"  # Porta para acesso ao SQS
    environment:
      - SERVICES=sqs,iam
      - DEFAULT_REGION=us-east-1
    networks:
      - microservice-fiap      
volumes:
   mongo-data:

networks:
  microservice-fiap:
    external: true
